menu:
  Index:
    url: /
    External: false
    name: 首页
  Tags:
    url: /tags
    External: false
    name: 标签
  Categories:
    url: /categories
    External: false
    name: 分类
  Archives:
    url: /archives
    External: false
    name: 归档
  About:
    url: /about
    External: false
    name: 关于

# 联系方式
contact:
  github: "https://github.com/f-dong"
  twitter:
  weibo:
  zhihu:
  facebook:

# 首页是否显示封面图片
showFeatureImage: true

# 首页头像图片
avatar: /images/avatar.png

# 谷歌统计 跟踪 ID
ga:

# Gittalk 评论组件
# See: https://github.com/gitalk/gitalk/
gitalk:
  enable: false
  clientId:
  clientSecret:
  repository:
  owner:

#ICP备案信息尾部显示
icp:
  enable: false
  url: # 备案链接
  text: # 备案信息

# 是否使用 bootcdn
use_bootcdn: true
